import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head';
import {Montserrat} from "@next/font/google"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["400", "700"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      </Head>
      <body>{children}</body>
    </html>
  )
}
